config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'order_forms#index'
  resources :orders
  get 'purchase', to: 'purchase#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :user
	default_scope { order(created_at: :asc) }


	validates :first_name, presence: true
	validates :last_name, presence: true
	validates :item, presence: true
	validates :size, presence: true
	validates :quantity, presence: true
	validates :color, presence: true
	validates :cost, presence: true
	
	
	def price
		case self.item
		when "jacket $30"
			@amount = 10
			self.cost = 10
		when "shirt $20"
			@amount = 25
			self.cost = 25
		when "pullover $50"
			@amount = 50
			self.cost = 50
		end
	end
	
end

app/models/user.rb
class User < ApplicationRecord
	has_many :orders


 # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable

  def admin?
  	admin
  end


end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
	skip_before_action :verify_authenticity_token, :only => :create
	before_action :authenticate_user!

	def index
		@orders = Order.all

	end
	def new
		@order = Order.new
		
	end

	def show
		@order = Order.find(params[:id])
	end

	def create
		@order = current_user.orders.create(order_params)
		
			
			  # Amount in cents
   
	@amount = (@order.price * 100).to_i	
	

    customer = Stripe::Customer.create(
      email: params[:stripeEmail],
      source: params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      customer: customer.id,
      amount: @amount,
      description: 'Rails Stripe customer',
      currency: 'usd'
    )
   
    redirect_to admin_order_path(@order)

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to root_path
		
	end

	private 

	def order_params
		params.require(:order).permit(:first_name, :last_name, :item, :size, :quantity, :color, :description, :cost)

	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
end

app/controllers/order_forms_controller.rb
class OrderFormsController < ApplicationController
before_action :authenticate_user!


def index
		
	end

	
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  skip_before_action :verify_authenticity_token, :only => :create
  before_action :authenticate_user!

  def index
    @orders = Order.all

  end
  def purchase
  end
  def new
    @order = Order.new
    
  end

  def show
    @order = Order.find(params[:id])
  end

  def edit 
    @order = Order.find(params[:id])

  end

  def update
    @order = Order.find(params[:id])
    @order.update_attributes(order_params)
    redirect_to orders_path
  end 

  def destroy
    @order = Order.find(params[:id])
    @order.destroy
    redirect_to orders_path

  end

  def create
    if current_user && current_user.admin?

      current_user.orders.create(order_params)

      redirect_to order_path(Order.last.id)
return
   end
    if current_user && !current_user.admin?
 current_user.orders.create(order_params)
        # Amount in cents

        @amount = (Order.last.cost * 100).to_i 


        customer = Stripe::Customer.create(
          email: params[:stripeEmail],
          source: params[:stripeToken]
          )

        charge = Stripe::Charge.create(
          customer: customer.id,
          amount: @amount,
          description: 'Rails Stripe customer',
          currency: 'usd'
          )
      end
      

      redirect_to order_path(Order.last.id)

    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to root_path

    end
    

    private 

    def order_params
      params.require(:order).permit(:first_name, :last_name, :item, :size, :quantity, :color, :description, :cost)

    end
    def current_order
@current_order ||=Order.find(params[:id])
    end

  end

app/controllers/purchase_controller.rb
class PurchaseController < ApplicationController
def show
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/order_forms_helper.rb
module OrderFormsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/purchase_helper.rb
module PurchaseHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MoabOrders</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/7e4250d31c.js"></script>
</head>

<body style="background-color:#00A9E0;">
    <font color="white">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a routerLink="/" class="navbar-brand" href="/">MOAB Jacket orders</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/orders/new">Place Order</a>
                    </li>
                </ul>
                <ul class="navbar-nav">
                    <% if user_signed_in? %>
                    <li class="nav-item">
                        <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
                    </li>
                    <% else %>
                    <li class="nav-item">
                        <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
                    </li>
                    <% end %>
                </ul>
        </nav>
        <% if notice.present? %>
        <p class="alert alert-info">
            <%= notice %>
        </p>
        <% end %>
        <% if alert.present? %>
        <p class="alert alert-danger">
            <%= alert %>
        </p>
        <% end %>
        </div>
        </nav>
        <%= yield %>
</body>

</html>

app/views/order_forms/index.html.erb
<div class="booyah-box col-10 offset-1 home-box">
    <h1 class="text-center">MOAB Jacket Orders Homepage </h1>
    <div class="col-10 offset-1">
        <div class="text-center">
            <% if current_user && current_user.admin? %>
            <%= link_to "Order index page", orders_path, class: 'btn btn-primary btn-large' %>
            <br />
            <br />
            <%= link_to "Purchase Order", purchase_path, class: 'btn btn-primary btn-large' %>
            <% end %>
            <br />
            <br />
            <%= link_to 'Order Form', new_order_path, class: 'btn btn-primary btn-large' %>
        </div>
        <br />
    </div>
</div>

app/views/orders/edit.html.erb
<br />
<br />
<br />
<div class=" text-center booyah-box col-10 offset-1">
    <h1 class="orders"> Orders</h1>
    <%= simple_form_for @order, url: order_path do |f| %>
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :item, :collection => ["jacket $30", "shirt $20", "pullover $50"]%>
    <%= f.input :quantity %>
    <%= f.input :size, :collection =>%w[XS S M L XL XXL] %>
    <%= f.input :color, :collection => %w[red yellow blue grey] %>
    <%= f.input :cost, :as => :hidden, input_html: {id: "order_cost"} %>
    <%= f.submit "Update", class: 'btn btn-primary btn-large' %>
    <p id="test">
    </p>
    <% end %>
    <br />

app/views/orders/index.html.erb
<br />
<div class="booyah-box col-10 offset-1 ">
    <h1 class="text-center">MOAB Orders</h1>
    <hr />
    <div id="show-when-small">
        <h3 class="text-center"> Your screen is too small.<br />
            Flip to landscape mode to view orders.</h3>
    </div>
    <div id="hide-when-small">
        <div class="container-fluid">
            <div class="row ">
                <div class="col-1">
                    <h3 class="index-size">
                        Id
                    </h3>
                </div>
                <div class="col-2">
                    <h3 class="index-size">
                        Name
                    </h3>
                </div>
                <div class="col-2">
                    <h3 class="index-size">
                        Item
                    </h3>
                </div>
                <div class="col-1">
                    <h3 class="index-size">
                        Size
                    </h3>
                </div>
                <div class="col-1">
                    <h3 class="index-size">
                        Qty
                    </h3>
                </div>
                <div class="col-2">
                    <h3 class="index-size">
                        Color
                    </h3>
                </div>
                <div div class="col-3">
                    <h3 class="index-size">
                        Cost
                    </h3>
                </div>
            </div>
            <% @orders.each do |order| %>
            <div class="row  margin-index">
                <div class="col-1">
                    <h3 class="index-size">
                        <%= order.id %>
                    </h3>
                </div>
                <div class="col-2">
                    <h3 class="index-size">
                        <%= order.first_name %>
                        <%= order.last_name %>
                    </h3>
                </div>
                <div class="col-2">
                    <h3 class="index-size">
                        <%= order.item %>
                    </h3>
                </div>
                <div class="col-1">
                    <h3 class="index-size">
                        <%= order.size %>
                    </h3>
                </div>
                <div class="col-1">
                    <h3 class="index-size">
                        <%= order.quantity %>
                    </h3>
                </div>
                <div class="col-2">
                    <h3 class="index-size">
                        <%= order.color %>
                    </h3>
                </div>
                <div class="col-3">
                    <h3 class="index-size">
                        <span class="badge badge-default">
                            <%= number_to_currency order.cost %>
                        </span>
                        &nbsp;&nbsp;
                        <%=link_to  edit_order_path(order),  class: 'edit-symbol' do %>
                        <i class="far fa-edit" style="color:white"></i>
                        <% end %>&nbsp;&nbsp;
                        <%= link_to order_path(order), method: :delete, data: {confirm: 'Are you sure you want to delete this?'},class: 'delete-symbol' do %>
                        <i class="far fa-trash-alt" style='color:white'></i>
                        <% end %>
                    </h3>
                </div>
            </div>
            <div class="underline">
            </div>
            <% end %>
        </div>
        <br />
        <div class="col-12 text-center">
            <%= link_to 'Homepage', root_path, class: 'btn btn-primary btn-large' %>
            <%= link_to 'Order Form', new_order_path, class: 'btn btn-primary btn-large' %>
        </div>
        <br />
        <div class="col-12 text-center">
            <%= link_to 'Purchase Form', purchase_path, class: 'btn btn-primary btn-large' %>
        </div>
        <br />
    </div>
</div>

app/views/orders/new.html.erb
<br />
<br />
<br />
<div class=" text-center booyah-box col-10 offset-1">
    <h1 class="orders"> Orders</h1>
    <%= simple_form_for @order, url: orders_path do |f| %>
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :item, :collection => ["shirt $20", "jacket $30","pullover $50"]%>
    <%= f.input :quantity %>
    <%= f.input :size, :collection =>%w[XS S M L XL XXL] %>
    <%= f.input :color, :collection => %w[red yellow blue grey] %>
    <%= f.input :cost, :as => :hidden, input_html: {id: "order_cost"} %>
    <p id="test">
    </p>
    <br />
    <% if current_user && !current_user.admin? %>
    <%= form_tag orders_path(@order) do %>
    </article>
    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button" data-key="<%= Rails.configuration.stripe[:publishable_key] %>" data-description="Cost of Methodist Olive Branch apparel" data-email="<%= current_user.email %>" data-amount="" data-locale="auto">
    </script>
    <% end %>
    <br />
    <% elsif current_user && current_user.admin? %>
    <%= f.submit "Admin Accepting Cash", class: 'cash btn btn-primary btn-large' %>
    <% end %>
    <% end %>
    <br />
</div>

app/views/orders/show.html.erb
<br />
<div class="booyah-box  show-box col-10 offset-1">
    <h1 class="text-center thanks">Thank You for Your Order! </h1>
    <div class="col-10 offset-1">
        <h2> Name:
            <%= @order.first_name %>
            <%= @order.last_name %>
        </h2>
    </div>
    <div class="col-10 offset-1">
        <h2> Item:
            <%= @order.item %>
        </h2>
    </div>
    <div class="col-10 offset-1">
        <h2> Quantity:
            <%= @order.quantity %>
        </h2>
    </div>
    <div class="col-10 offset-1">
        <h2> Size:
            <%= @order.size %>
        </h2>
    </div>
    <div class="col-10 offset-1">
        <h2> Color:
            <%= @order.color %>
        </h2>
    </div>
    <div class="col-10 offset-1">
        <h2> Cost:
            <span class="badge badge-default">
                <%= number_to_currency @order.cost %>
            </span>
        </h2>
    </div>
    <br />
    <div class="col-12 text-center">
        <%= link_to 'Homepage', root_path, class: 'btn btn-primary btn-large' %>
    </div>
    <br />
</div>